#!/home/kain/eggdrop/builddir/src/eggdrop
# Test config pointing at builddir modules

set mod-path "/home/kain/eggdrop/builddir/src/"

loadmodule pbkdf2
loadmodule blowfish
loadmodule channels
loadmodule server
loadmodule ctcp
loadmodule irc
loadmodule notes
loadmodule console
loadmodule uptime

set nick "EggTest"
set altnick "EggTest?"
set realname "Eggdrop Test Bot"
set username "eggtest"
logfile mco * "eggtest.log"
set logfile-suffix ""
set max-logsize 0
set userfile "eggtest.user"
set chanfile "eggtest.chan"
set pidfile "eggtest.pid"
set notefile "eggtest.notes"

set admin "Test <test@example.com>"
set network "TestNet"
set timezone "UTC"
set owner "TestOwner"

server add 95.216.225.58 6667
