name: Eggdrop Compile

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  default-build:
    name: Compile Test
    strategy:
      matrix:
        cc: [ 'gcc', 'clang' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install clang meson ninja-build tcl tcl-dev openssl libssl-dev
    - uses: ammaraskar/gcc-problem-matcher@master
      if: ${{ matrix.cc == 'gcc' }}
    - name: Build
      env:
        CC: ${{ matrix.cc }}
      run: meson setup build && ninja -j$(nproc) -C build
  feature-test:
    name: Features
    continue-on-error: true
    needs: default-build
    strategy:
      matrix:
        opt_tls:  [ '', '-Dtls=disabled' ]
        opt_ipv6: [ '', '-Dipv6=false' ]
        opt_tdns: [ '', '-Dtdns=false' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install meson ninja-build tcl tcl-dev openssl libssl-dev
    - uses: ammaraskar/gcc-problem-matcher@master
    - name: Build
      run: meson setup build ${{ matrix.opt_tls }} ${{ matrix.opt_ipv6 }} ${{ matrix.opt_tdns }} && ninja -j$(nproc) -C build
